name: "Deploy test env"
description: "Deploy test env"
inputs:
  name:
    description: "Name of the test env"
    required: true
    default: "ci"
  namespace:
    description: "Namespace of the test env"
    required: false
    default: "ci"
runs:
  using: "composite"
  steps:
    - name: Install environment
      shell: bash
      env:
        HELM_DRIVER: configmap
      run: |
        helm -n ${{ inputs.namespace }} upgrade --install ${{ inputs.name }} charts/kubepmix --set-string "additionalObjectSelector.matchLabels.ci\.kubepmix\.dev/test-id=${{ inputs.name }}" --wait --create-namespace
