name: "Deploy test env"
description: "Deploy test env"
inputs:
  name:
    description: "Name of the test env"
    required: true
    default: "ci"
runs:
  using: "composite"
  steps:
    - name: Install environment
      shell: bash
      run: |
        set -euo pipefail

        TEST_ENV_NAME="${{ inputs.name }}"
        TEST_ENV_NAMESPACE="${{ inputs.name }}"
        REPO_SSH_URL="ssh://git@github.com/${{ github.repository }}.git"
        REF_BRANCH="${{ github.ref_name }}"
        REF_COMMIT="${{ github.sha }}"

        cat <<EOF | kubectl apply -f -
        ---
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: GitRepository
        metadata:
          name: $TEST_ENV_NAME
          namespace: arc
        spec:
          interval: 5m0s
          url: $REPO_SSH_URL
          ref:
            branch: $REF_BRANCH
            commit: $REF_COMMIT
          secretRef:
            name: kubepmix-deploykey
        ---
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: $TEST_ENV_NAME
          namespace: arc
        spec:
          interval: 15m
          timeout: 5m
          chart:
            spec:
              chart: ./charts/kubepmix
              sourceRef:
                kind: GitRepository
                name: $TEST_ENV_NAME
              interval: 5m
          releaseName: $TEST_ENV_NAME
          targetNamespace: $TEST_ENV_NAMESPACE
          waitStrategy:
            name: poller
          install:
            disableWait: false
            createNamespace: true
          healthCheckExprs:
            - apiVersion: v1
              kind: Pod
              current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
        EOF

        kubectl wait --for=condition=Ready "helmrelease/$TEST_ENV_NAME" --timeout=10m
