networks:
  # "Management" network - between PMIx server and clients
  pmix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/24
  # MPI BTL network - between MPI ranks
  mpi-btl-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.199.0.0/24

services:
  server:
    # image: ghcr.io/kubepmix/kubepmix:0.0.80
    image: smiec3
    environment:
      # Bootstrap namespace
      KUBE_PMIX_NAMESPACE_NAME: "mynamespace"
      KUBE_PMIX_JOB_SIZE: "2"

      # Fix PMIx server interface and port
      PMIX_MCA_ptl_tcp_ipv4_port: "3333"
      PMIX_MCA_ptl_tcp_if_include: "eth0"

      # Required
      PMIX_MCA_psec: "none" # Do not check processes UID and GUID

    healthcheck:
      test: ["CMD", "python3", "is_healthy.py"]
      start_period: 3s
      interval: 5s
      timeout: 1s
      retries: 5

    networks:
      pmix-net:
        ipv4_address: 10.3.0.10 # Fix address, DNS not supported in pmix server uri

  simplempi0:
    image: ghcr.io/kubepmix/images/simplempi:latest
    environment:
      # Rank information - usually set by setup_fork()
      PMIX_SERVER_URI2: "kubepmix.1;tcp4://10.3.0.10:3333"
      PMIX_NAMESPACE: "mynamespace"
      PMIX_RANK: "0"

      # Required
      PMIX_SECURITY_MODE: "none"
      PMIX_GDS_MODULE: "hash"

      # BTL settings
      OMPI_MCA_btl: "tcp,self"
      OMPI_MCA_btl_tcp_if_include: "10.199.0.0/24" # Use mpi-btl-net for MPI communication

      # Application settings, run 5 all gathers with 1 second in between, sleep 5 second
      GATHER_TIME: "1"
      GATHER_COUNT: "5"
      SLEEP_TIME: "1"
      SLEEP_COUNT: "5"

    depends_on:
      server:
        condition: service_healthy
        restart: true # Restart when server restarts

    networks:
      - pmix-net
      - mpi-btl-net

  simplempi1:
    image: ghcr.io/kubepmix/images/simplempi:latest
    environment:
      # Rank information - usually set by setup_fork()
      PMIX_SERVER_URI2: "kubepmix.1;tcp4://10.3.0.10:3333"
      PMIX_NAMESPACE: "mynamespace"
      PMIX_RANK: "1"

      # Required
      PMIX_SECURITY_MODE: "none"
      PMIX_GDS_MODULE: "hash"

      # Application settings, run 5 all gathers with 1 second in between, sleep 1 second
      SLEEP_TIME: "1"
      SLEEP_COUNT: "1"
      GATHER_TIME: "1"
      GATHER_COUNT: "5"

      # BTL settings
      OMPI_MCA_btl: "tcp,self"
      OMPI_MCA_btl_tcp_if_include: "10.199.0.0/24" # Use mpi-btl-net for MPI communication

    depends_on:
      server:
        condition: service_healthy
        restart: true # Restart when server restarts

    networks:
      - pmix-net
      - mpi-btl-net
