# Assumes repo is cloned by a calling workflow
name: "Build image"
description: "Build image"
inputs:
  tags:
    description: "Image tags"
  build-args:
    description: "Build arguments"

runs:
  using: "composite"
  steps:
    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: remote
        endpoint: tcp://buildkitd.buildkit:1234

    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        context: ./src
        push: true
        tags: ${{ inputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build-args }}
