# Assumes repo is cloned and GH is authenticated by a calling workflow
name: "Build chart"
description: "Build helm chart"
inputs:
  tag:
    description: "Image and helm chart tag"

runs:
  using: "composite"
  steps:
    - name: Package and push chart
      run: |
        helm package charts/kubepmix --version ${{ inputs.tag }} --app-version ${{ inputs.tag }}
        helm push kubepmix-${{ inputs.tag }}.tgz oci://ghcr.io/kubepmix/charts
