apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kube-pmix-selfsigned
  namespace: kube-pmix
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-pmix-tls
  namespace: kube-pmix
spec:
  secretName: kube-pmix-tls
  issuerRef:
    name: kube-pmix-selfsigned
    kind: Issuer
  dnsNames:
    - kube-pmix
    - kube-pmix.kube-pmix.svc
    - kube-pmix.kube-pmix.svc.cluster.local
