apiVersion: v1
kind: Namespace
metadata:
  name: kube-pmix
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-pmix
  namespace: kube-pmix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-pmix
  namespace: kube-pmix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-pmix
  template:
    metadata:
      labels:
        app: kube-pmix
    spec:
      serviceAccountName: kube-pmix
      containers:
        - name: kube-pmix
          image: ghcr.io/kubepmix/kubepmix:0.0.12
          ports:
            - name: pmix
              containerPort: 3333
              protocol: TCP
            - name: webhook
              containerPort: 8443
              protocol: TCP
          env:
            - name: PMIX_MCA_psec
              value: "none" # Do not check processes UID and GUID
            - name: PMIX_MCA_ptl_tcp_ipv4_port
              value: "3133"
            - name: PMIX_MCA_ptl_tcp_if_exclude
              value: "lo"
            - name: KUBE_PMIX_WEBHOOK_ENABLED
              value: "true"
            - name: KUBE_PMIX_WEBHOOK_PORT
              value: "8443"
            - name: KUBE_PMIX_TLS_CERT
              value: /tls/tls.crt
            - name: KUBE_PMIX_TLS_KEY
              value: /tls/tls.key
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: kube-pmix-tls
---
apiVersion: v1
kind: Service
metadata:
  name: kube-pmix
  namespace: kube-pmix
spec:
  selector:
    app: kube-pmix
  ports:
    - name: pmix
      port: 3333
      targetPort: pmix
      protocol: TCP
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
