# When true - inject namespaceSelector to Release namespace in the Mutating webhook
namespaced: "false"

# additional job & pod selector for mutating webhook. useful for CI jobs collocated in a single namespace
# additionalObjectSelector:
#   matchLabels:
#     ci.kubepmix.dev/job-id: "123456"

server:
  image:
    repository: ghcr.io/kubepmix/kubepmix
    tag: 0.0.12
  webhook:
    port: 8443
  pmix:
    port: 3333
    envs:
      - name: PMIX_MCA_ptl_tcp_if_include
        value: "eth0"
