name: "Destroy test env"
description: "Destroy test env"
inputs:
  name:
    description: "Name of the test env"
    required: true
    default: "ci"
runs:
  using: "composite"
  steps:
    - name: Install environment
      shell: bash
      run: |
        set -euo pipefail
        kubectl -n "${{ inputs.name }}" delete helmrelease "${{ inputs.name }}" --ignore-not-found=true --wait=true
        kubectl -n "${{ inputs.name }}" delete gitrepository "${{ inputs.name }}" --ignore-not-found=true --wait=true
        kubectl delete ns "${{ inputs.name }}" --ignore-not-found=true --wait
