name: Main
run-name: Main

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "charts/**"
    tags:
      - "*"

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: PR Test
    uses: ./.github/workflows/rw-test.yaml
    secrets: inherit
