name: Release
run-name: Release

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  create-release:
    needs: build-image
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: semver
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          major_pattern: "/!:|BREAKING CHANGE:/"
          major_regexp_flags: ""
          minor_pattern: "/feat(\\(.+\\))?:/"
          minor_regexp_flags: ""
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: true

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semver.outputs.version_tag }}
          name: KubePMIx ${{ steps.semver.outputs.version }}
          body: |
            Release created from branch ${{ github.ref_name }} with commit ${{ github.sha }}.
            Image: ghcr.io/${{ github.repository }}:${{ steps.semver.outputs.version }}
