name: Release
run-name: Release

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    name: Build release image
    runs-on: kubepmix-selfhosted
    outputs:
      version: ${{ steps.semver.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: semver
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          major_pattern: "/!:|BREAKING CHANGE:/"
          major_regexp_flags: ""
          minor_pattern: "/feat(\\(.+\\))?:/"
          minor_regexp_flags: ""
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: true

      - uses: ./.github/actions/build-image
        id: build-image
        with:
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.semver.outputs.version }}
            ghcr.io/${{ github.repository }}:latest

  create-release:
    name: Create release
    needs: build-image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.build-image.outputs.version }}
          name: KubePMIx ${{ needs.build-image.outputs.version }}
          body: |
            Release created from branch ${{ github.ref_name }} with commit ${{ github.sha }}.
            Image: ghcr.io/${{ github.repository }}:${{ needs.build-image.outputs.version }}
