name: Test
run-name: Test KubePMIx

on:
  workflow_dispatch:
  schedule:
    - cron: "7 * * * *" # 7 past every hour
  push:
    branches:
      - testv1
      - main

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: kubepmix-selfhosted-test
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: deploy-test-env
        uses: ./.github/actions/deploy-test-env
        with:
          name: ci-${{ github.run_id }}

      - name: destroy-test-env
        uses: ./.github/actions/destroy-test-env
        if: always()
        with:
          name: ci-${{ github.run_id }}
