name: Test
run-name: "Test KubePMIx (${{ github.event_name == 'pull_request' && format('PR #{0}', github.event.pull_request.number) || github.ref_name }})"

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "7 * * * *" # 7 past every hour
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "charts/**"

permissions:
  contents: read

jobs:
  test:
    name: Run Test
    runs-on: kubepmix-selfhosted-test
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/build-image
        id: build-image
        with:
          tags: registry.registry:5000/${{ github.repository }}:${{ github.sha }}

      - name: Deploy test environment
        uses: ./.github/actions/deploy-test-env
        with:
          name: ci-${{ github.run_id }}
          image: registry.registry:5000/${{ github.repository }}:${{ github.sha }}

      - name: Run Kubernetes tests
        working-directory: test/kubernetes
        env:
          TEST_ID: ci-${{ github.run_id }}
        shell: bash
        run: |
          pytest -sv

      - name: Destroy test environment
        uses: ./.github/actions/destroy-test-env
        if: always()
        with:
          name: ci-${{ github.run_id }}
