name: Test
run-name: "Test KubePMIX (${{ github.event_name == 'pull_request' && format('PR #{0}', github.event.pull_request.number) || github.ref_name }})"

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "7 * * * *" # 7 past every hour
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "charts/**"

permissions:
  contents: read

jobs:
  build-image:
    name: Build CI image
    uses: ./.github/workflows/rw-build-image-ci.yaml
    secrets: inherit

  test:
    name: Run Test
    needs: build-image
    runs-on: kubepmix-selfhosted-test
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Deploy test environment
        uses: ./.github/actions/deploy-test-env
        with:
          name: ci-${{ github.run_id }}
          image: ${{ needs.build-image.outputs.tags }}

      - name: Run Job tests
        working-directory: test/jobs
        env:
          TEST_ID: ci-${{ github.run_id }}
        shell: bash
        run: |
          pytest -sv

      - name: Destroy test environment
        uses: ./.github/actions/destroy-test-env
        if: always()
        with:
          name: ci-${{ github.run_id }}
